// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: oracle/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetStockRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetStockRequest) Reset()         { *m = QueryGetStockRequest{} }
func (m *QueryGetStockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetStockRequest) ProtoMessage()    {}
func (*QueryGetStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{0}
}
func (m *QueryGetStockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStockRequest.Merge(m, src)
}
func (m *QueryGetStockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStockRequest proto.InternalMessageInfo

func (m *QueryGetStockRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetStockResponse struct {
	Stock *Stock `protobuf:"bytes,1,opt,name=Stock,proto3" json:"Stock,omitempty"`
}

func (m *QueryGetStockResponse) Reset()         { *m = QueryGetStockResponse{} }
func (m *QueryGetStockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetStockResponse) ProtoMessage()    {}
func (*QueryGetStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{1}
}
func (m *QueryGetStockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetStockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetStockResponse.Merge(m, src)
}
func (m *QueryGetStockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetStockResponse proto.InternalMessageInfo

func (m *QueryGetStockResponse) GetStock() *Stock {
	if m != nil {
		return m.Stock
	}
	return nil
}

type QueryAllStockRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStockRequest) Reset()         { *m = QueryAllStockRequest{} }
func (m *QueryAllStockRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllStockRequest) ProtoMessage()    {}
func (*QueryAllStockRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{2}
}
func (m *QueryAllStockRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStockRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStockRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStockRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStockRequest.Merge(m, src)
}
func (m *QueryAllStockRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStockRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStockRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStockRequest proto.InternalMessageInfo

func (m *QueryAllStockRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllStockResponse struct {
	Stock      []*Stock            `protobuf:"bytes,1,rep,name=Stock,proto3" json:"Stock,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllStockResponse) Reset()         { *m = QueryAllStockResponse{} }
func (m *QueryAllStockResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllStockResponse) ProtoMessage()    {}
func (*QueryAllStockResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_562b782cb9ac197e, []int{3}
}
func (m *QueryAllStockResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllStockResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllStockResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllStockResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllStockResponse.Merge(m, src)
}
func (m *QueryAllStockResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllStockResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllStockResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllStockResponse proto.InternalMessageInfo

func (m *QueryAllStockResponse) GetStock() []*Stock {
	if m != nil {
		return m.Stock
	}
	return nil
}

func (m *QueryAllStockResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetStockRequest)(nil), "lovesh2407.OracleDemo.oracle.QueryGetStockRequest")
	proto.RegisterType((*QueryGetStockResponse)(nil), "lovesh2407.OracleDemo.oracle.QueryGetStockResponse")
	proto.RegisterType((*QueryAllStockRequest)(nil), "lovesh2407.OracleDemo.oracle.QueryAllStockRequest")
	proto.RegisterType((*QueryAllStockResponse)(nil), "lovesh2407.OracleDemo.oracle.QueryAllStockResponse")
}

func init() { proto.RegisterFile("oracle/query.proto", fileDescriptor_562b782cb9ac197e) }

var fileDescriptor_562b782cb9ac197e = []byte{
	// 407 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x93, 0x4d, 0x6b, 0x1a, 0x41,
	0x18, 0xc7, 0x9d, 0x6d, 0x2d, 0x65, 0x0a, 0x3d, 0x0c, 0x2d, 0x14, 0x91, 0xa5, 0xac, 0xd4, 0x8a,
	0x85, 0x19, 0x5d, 0x0b, 0xa5, 0x47, 0x4b, 0xa9, 0xf4, 0xd4, 0x66, 0x73, 0xcb, 0x21, 0x30, 0xbb,
	0x0e, 0xeb, 0x92, 0x75, 0x67, 0x75, 0x46, 0x89, 0x84, 0x5c, 0xf2, 0x09, 0x02, 0x39, 0xe6, 0x12,
	0xf2, 0x69, 0x72, 0x8b, 0x90, 0x4b, 0x8e, 0x41, 0xf3, 0x41, 0x82, 0x33, 0x23, 0xab, 0x26, 0x31,
	0x7a, 0x7d, 0xf6, 0xff, 0xf2, 0x7b, 0xf6, 0xd9, 0x85, 0x88, 0xf7, 0x69, 0x10, 0x33, 0xd2, 0x1b,
	0xb0, 0xfe, 0x08, 0xa7, 0x7d, 0x2e, 0x39, 0x2a, 0xc6, 0x7c, 0xc8, 0x44, 0xc7, 0xfd, 0x5e, 0xfb,
	0x81, 0xff, 0xa9, 0xc7, 0xbf, 0x59, 0x97, 0x63, 0xad, 0x2c, 0x14, 0x43, 0xce, 0xc3, 0x98, 0x11,
	0x9a, 0x46, 0x84, 0x26, 0x09, 0x97, 0x54, 0x46, 0x3c, 0x11, 0xda, 0x5b, 0xa8, 0x06, 0x5c, 0x74,
	0xb9, 0x20, 0x3e, 0x15, 0x26, 0x94, 0x0c, 0xeb, 0x3e, 0x93, 0xb4, 0x4e, 0x52, 0x1a, 0x46, 0x89,
	0x12, 0x1b, 0xed, 0xbc, 0x5b, 0x48, 0x1e, 0x1c, 0xe8, 0x99, 0x53, 0x86, 0x1f, 0x76, 0x66, 0xae,
	0x16, 0x93, 0xbb, 0xb3, 0xb1, 0xc7, 0x7a, 0x03, 0x26, 0x24, 0x7a, 0x0f, 0xad, 0xa8, 0xfd, 0x09,
	0x7c, 0x06, 0x95, 0xd7, 0x9e, 0x15, 0xb5, 0x1d, 0x0f, 0x7e, 0x5c, 0xd1, 0x89, 0x94, 0x27, 0x82,
	0xa1, 0x9f, 0x30, 0xaf, 0x06, 0x4a, 0xfb, 0xce, 0x2d, 0xe1, 0x75, 0xcb, 0x60, 0xed, 0xd5, 0x0e,
	0x67, 0xdf, 0x74, 0x37, 0xe3, 0x78, 0xa9, 0xfb, 0x0f, 0x84, 0x19, 0xbb, 0xc9, 0x2d, 0x63, 0xbd,
	0x28, 0x9e, 0x2d, 0x8a, 0xf5, 0xdb, 0x33, 0x8b, 0xe2, 0xff, 0x34, 0x64, 0xc6, 0xeb, 0x2d, 0x38,
	0x9d, 0x73, 0x60, 0xa0, 0xb3, 0x82, 0xc7, 0xd0, 0xaf, 0xb6, 0x83, 0x46, 0xad, 0x25, 0x38, 0x4b,
	0xc1, 0x7d, 0x7d, 0x11, 0x4e, 0xf7, 0x2e, 0xd2, 0xb9, 0xd7, 0x16, 0xcc, 0x2b, 0x3a, 0x74, 0x09,
	0x0c, 0x0e, 0x72, 0xd7, 0x83, 0x3c, 0x75, 0xa9, 0x42, 0x63, 0x2b, 0x8f, 0x06, 0x71, 0x6a, 0x27,
	0x37, 0xf7, 0x67, 0x56, 0x15, 0x55, 0x48, 0x66, 0x26, 0x99, 0x99, 0x2c, 0x7e, 0x29, 0xe4, 0x28,
	0x6a, 0x1f, 0xa3, 0x0b, 0x00, 0xdf, 0xaa, 0x8c, 0x66, 0x1c, 0x6f, 0xc4, 0xb9, 0x72, 0xd5, 0x8d,
	0x38, 0x57, 0x0f, 0xe5, 0x7c, 0x53, 0x9c, 0x5f, 0x50, 0x69, 0x03, 0xce, 0x5f, 0x7f, 0xaf, 0x26,
	0x36, 0x18, 0x4f, 0x6c, 0x70, 0x37, 0xb1, 0xc1, 0xe9, 0xd4, 0xce, 0x8d, 0xa7, 0x76, 0xee, 0x76,
	0x6a, 0xe7, 0xf6, 0x48, 0x18, 0xc9, 0xce, 0xc0, 0xc7, 0x01, 0xef, 0x3e, 0x13, 0x74, 0x38, 0x8f,
	0x92, 0xa3, 0x94, 0x09, 0xff, 0x8d, 0xfa, 0x3b, 0x1a, 0x0f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xed,
	0x4b, 0xff, 0x21, 0xaf, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// this line is used by starport scaffolding # 2
	Stock(ctx context.Context, in *QueryGetStockRequest, opts ...grpc.CallOption) (*QueryGetStockResponse, error)
	StockAll(ctx context.Context, in *QueryAllStockRequest, opts ...grpc.CallOption) (*QueryAllStockResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Stock(ctx context.Context, in *QueryGetStockRequest, opts ...grpc.CallOption) (*QueryGetStockResponse, error) {
	out := new(QueryGetStockResponse)
	err := c.cc.Invoke(ctx, "/lovesh2407.OracleDemo.oracle.Query/Stock", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) StockAll(ctx context.Context, in *QueryAllStockRequest, opts ...grpc.CallOption) (*QueryAllStockResponse, error) {
	out := new(QueryAllStockResponse)
	err := c.cc.Invoke(ctx, "/lovesh2407.OracleDemo.oracle.Query/StockAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// this line is used by starport scaffolding # 2
	Stock(context.Context, *QueryGetStockRequest) (*QueryGetStockResponse, error)
	StockAll(context.Context, *QueryAllStockRequest) (*QueryAllStockResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Stock(ctx context.Context, req *QueryGetStockRequest) (*QueryGetStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Stock not implemented")
}
func (*UnimplementedQueryServer) StockAll(ctx context.Context, req *QueryAllStockRequest) (*QueryAllStockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StockAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Stock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Stock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lovesh2407.OracleDemo.oracle.Query/Stock",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Stock(ctx, req.(*QueryGetStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_StockAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllStockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).StockAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/lovesh2407.OracleDemo.oracle.Query/StockAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).StockAll(ctx, req.(*QueryAllStockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "lovesh2407.OracleDemo.oracle.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Stock",
			Handler:    _Query_Stock_Handler,
		},
		{
			MethodName: "StockAll",
			Handler:    _Query_StockAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "oracle/query.proto",
}

func (m *QueryGetStockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetStockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetStockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetStockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Stock != nil {
		{
			size, err := m.Stock.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStockRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStockRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStockRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllStockResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllStockResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllStockResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Stock) > 0 {
		for iNdEx := len(m.Stock) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Stock[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetStockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetStockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stock != nil {
		l = m.Stock.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStockRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllStockResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Stock) > 0 {
		for _, e := range m.Stock {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetStockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetStockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetStockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetStockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Stock == nil {
				m.Stock = &Stock{}
			}
			if err := m.Stock.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStockRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStockRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStockRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllStockResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllStockResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllStockResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stock", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Stock = append(m.Stock, &Stock{})
			if err := m.Stock[len(m.Stock)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
